-- LI-NING 라켓 데이터 INSERT
-- 실행 전 중복 확인: SELECT slug FROM rackets WHERE slug LIKE 'lining-%';

INSERT INTO rackets (slug, name, brand, price_range, weight, balance, flex, level, type, stat_power, stat_control, stat_speed, stat_durability, stat_repulsion, stat_maneuver, description, editor_pick, is_popular) VALUES

('lining-axforce-9',
 '리닝 엑스포스 9(LI-NING AXFORCE 9) 라켓',
 'LI-NING', '~5만원', '3U', 'head-heavy', 'flexible',
 ARRAY['왕초보','초심자'], ARRAY['공격형'],
 60, 50, 45, 65, 55, 45,
 '리닝 입문 라인의 가장 접근하기 쉬운 모델로, 알루미늄+카본 혼합 프레임이 내구성을 높였다. 헤드헤비 설계로 스매시에 자연스럽게 무게감이 실리며, 손목 부담을 줄인 장력 세팅이 왕초보에게 적합하다. 처음 라켓을 구매하는 분께 가성비 측면에서 가장 먼저 추천되는 모델이다.',
 false, true),

('lining-axforce-20',
 '리닝 엑스포스 20(LI-NING AXFORCE 20) 라켓',
 'LI-NING', '5~10만원', '4U', 'head-heavy', 'flexible',
 ARRAY['왕초보','초심자'], ARRAY['공격형'],
 68, 52, 50, 70, 60, 50,
 '풀 카본 프레임으로 업그레이드된 입문용 공격형 라켓으로, 소닉 붐 시스템과 박스 윙 프레임이 스매시 타격감을 높였다. 6.8mm 유연한 샤프트 덕분에 초보자도 쉽게 클리어와 스매시를 칠 수 있다. 뒷코트 스매시를 즐기는 입문자에게 적합한 첫 번째 카본 라켓이다.',
 false, false),

('lining-axforce-30-ex-light',
 '리닝 엑스포스 30 EX 라이트(LI-NING AXFORCE 30 EX-LIGHT) 라켓',
 'LI-NING', '5~10만원', '5U', 'head-heavy', 'flexible',
 ARRAY['초심자','D조'], ARRAY['공격형'],
 72, 55, 68, 68, 65, 65,
 '2025년 출시된 AXFORCE 30 시리즈의 경량 버전으로, 5U(약 75g)의 초경량 설계가 빠른 스윙 스피드와 민첩한 전환을 가능하게 한다. 소닉 붐 시스템과 고탄성 카본 파이버가 결합되어 가벼우면서도 스매시 파워가 충분히 전달된다. 공격적인 플레이를 지향하는 초심자~D조에게 가격 대비 만족도가 높은 선택이다.',
 true, true),

('lining-halbertec-5000',
 '리닝 하버텍 5000(LI-NING HALBERTEC 5000) 라켓',
 'LI-NING', '10~15만원', '4U', 'even', 'medium',
 ARRAY['초심자','D조'], ARRAY['올라운드'],
 60, 72, 60, 72, 62, 68,
 'HALBERTEC 시리즈의 입문형 모델로, 이븐 밸런스와 미디엄 플렉스가 공격과 수비 모두에 균형 잡힌 퍼포먼스를 제공한다. 밸런스 포인트 295mm 설계로 손목 부담이 적고, 초심자가 다양한 샷을 연습하기에 적합하다. 컨트롤 라켓을 원하는 입문자에게 HALBERTEC 시리즈의 첫 선택으로 추천된다.',
 false, false),

('lining-halbertec-6000',
 '리닝 하버텍 6000(LI-NING HALBERTEC 6000) 라켓',
 'LI-NING', '10~15만원', '5U', 'even', 'medium',
 ARRAY['초심자','D조'], ARRAY['올라운드'],
 62, 76, 64, 73, 65, 72,
 '하버텍 5000보다 소재 등급이 높아진 모델로, 슬림 6.8mm 샤프트가 빠른 스윙 시 채찍 효과를 강화한다. HDF 충격 흡수 시스템이 탑재되어 장시간 플레이 시 손목·팔꿈치 피로감을 줄여준다. 컨트롤 중심의 올라운드 플레이를 원하는 D조 플레이어에게 균형 잡힌 업그레이드 선택지다.',
 true, true),

('lining-halbertec-7000',
 '리닝 하버텍 7000(LI-NING HALBERTEC 7000) 라켓',
 'LI-NING', '10~15만원', '3U', 'even', 'medium',
 ARRAY['D조','C조'], ARRAY['올라운드'],
 65, 80, 62, 75, 68, 70,
 'HALBERTEC 시리즈의 준고급형으로, 미디엄 플렉스와 이븐 밸런스가 정확한 드롭샷·크로스코트 플레이에 최적화되어 있다. 고밀도 카본 파이버 프레임이 진동을 억제하면서도 반발력을 높여 안정적인 랠리 전개를 돕는다. 전략적 올라운드 플레이를 추구하는 D조~C조에게 적합하다.',
 false, false),

('lining-bladex-73-light',
 '리닝 블레이덱스 73 라이트(LI-NING BLADEX 73 LIGHT) 라켓',
 'LI-NING', '5~10만원', '6U', 'head-light', 'stiff',
 ARRAY['초심자','D조'], ARRAY['수비형','올라운드'],
 55, 75, 82, 70, 72, 85,
 '6U(74~80g) 초경량 설계에 헤드라이트 밸런스가 결합된 수비·속공 특화 모델로, 스티프 샤프트가 빠른 네트 대응과 드라이브 랠리에 유리하다. TB-Nano 기술로 경량임에도 프레임 강도가 우수하며, 최대 31lbs 장력까지 지원한다. 손목 스냅이 아직 부족한 초심자도 빠른 라켓 조작이 가능해 복식 입문자에게 특히 유용하다.',
 true, true),

('lining-windstorm-72',
 '리닝 윈드스톰 72(LI-NING WINDSTORM 72) 라켓',
 'LI-NING', '10~15만원', '6U', 'head-light', 'flexible',
 ARRAY['초심자','D조'], ARRAY['수비형'],
 48, 70, 88, 65, 68, 90,
 '72g의 초경량 프레임과 헤드라이트 밸런스(밸런스 포인트 315mm)가 조합되어 복식 경기에서 번개 같은 네트 반응과 드라이브를 가능하게 한다. 유연한 샤프트가 손목 스냅과 공의 에너지를 자연스럽게 연결하여 체력 소모 없이 빠른 랠리 유지가 쉽다. 스피드를 최우선으로 두는 복식 입문~D조 선수에게 리닝 라인업 중 가장 빠른 라켓이다.',
 false, true),

('lining-tectonic-7',
 '리닝 텍토닉 7(LI-NING TECTONIC 7) 라켓',
 'LI-NING', '10~15만원', '4U', 'even', 'medium',
 ARRAY['D조','C조'], ARRAY['올라운드'],
 68, 78, 70, 75, 70, 73,
 '선더볼트 클라우드 테크놀로지와 T1100G 고탄성 카본 파이버 프레임이 결합된 올라운드 라켓으로, 드라이브·드롭·클리어 등 모든 샷을 포용력 있게 처리한다. 이븐 밸런스와 미디엄 플렉스 조합이 손목·팔꿈치 부담을 줄여주어 입문기에 다양한 기술을 익히기 좋다. 전문가 수준의 내구성과 완성도를 갖추면서도 D조에게 쉽게 다가갈 수 있는 준프로용 라켓이다.',
 true, false),

('lining-bladex-sonar',
 '리닝 블레이덱스 소나(LI-NING BLADEX SONAR) 라켓',
 'LI-NING', '5~10만원', '4U', 'even', 'medium',
 ARRAY['초심자','D조'], ARRAY['올라운드'],
 62, 70, 65, 72, 65, 68,
 '리닝 한국 공식몰 베스트셀러 상위권 모델로, 에어로다이나믹 BLADEX 프레임 설계와 미디엄 플렉스가 균형 잡힌 타구감을 제공한다. 4U 무게감과 이븐 밸런스가 공수 전환이 잦은 복식 초심자와 D조에게 부담 없는 조작성을 선사한다. 리닝을 처음 접하는 플레이어의 가성비 첫 선택으로 적합하다.',
 false, true);
