-- MIZUNO 라켓 데이터 INSERT
-- 실행 전 중복 확인: SELECT slug FROM rackets WHERE slug LIKE 'mizuno-%';

INSERT INTO rackets (slug, name, brand, price_range, weight, balance, flex, level, type, stat_power, stat_control, stat_speed, stat_durability, stat_repulsion, stat_maneuver, description, editor_pick, is_popular) VALUES

('mizuno-carbopro-829',
 '미즈노 카보 프로 829(MIZUNO CARBO PRO 829) 라켓',
 'MIZUNO', '5~10만원', '4U', 'even', 'medium',
 ARRAY['왕초보','초심자'], ARRAY['올라운드'],
 48, 72, 65, 70, 55, 75,
 '이븐 밸런스 설계로 공수 모두 고르게 사용할 수 있는 풀 카본 입문용 라켓이다. 5만원대 가성비 가격에 카본 소재의 내구성을 갖추어 처음 배드민턴을 시작하는 분에게 부담 없는 선택지다.',
 false, true),

('mizuno-carbopro-823',
 '미즈노 카보 프로 823(MIZUNO CARBO PRO 823) 라켓',
 'MIZUNO', '5~10만원', '4U', 'head-heavy', 'medium',
 ARRAY['왕초보','초심자'], ARRAY['공격형'],
 62, 60, 60, 68, 62, 65,
 '헤드헤비 밸런스와 미디엄 강성을 갖춘 입문용 공격형 라켓이다. AeroBox 프레임 구조로 스매시 시 안정적인 타구감을 제공하며, 일본 HM 그라파이트 소재를 가성비 있는 가격에 경험할 수 있다.',
 false, true),

('mizuno-technoblade-688',
 '미즈노 테크노블레이드 688(MIZUNO TECHNOBLADE 688) 라켓',
 'MIZUNO', '5~10만원', '4U', 'head-heavy', 'flexible',
 ARRAY['왕초보','초심자'], ARRAY['공격형'],
 58, 55, 70, 72, 60, 72,
 '풀 카본 소재에 헤드헤비 밸런스와 유연한 샤프트를 조합한 입문용 라켓이다. 스윙 시 헤드 무게가 자연스럽게 실려 초보자도 스매시 파워를 내기 쉬우며, 4가지 컬러 선택지를 제공한다.',
 true, true),

('mizuno-altius-02-solear',
 '미즈노 알티우스 02 소울라(MIZUNO ALTIUS 02 SOLEAR) 라켓',
 'MIZUNO', '10~15만원', '4U', 'head-light', 'flexible',
 ARRAY['왕초보','초심자'], ARRAY['수비형'],
 40, 80, 78, 68, 55, 85,
 '헤드라이트 밸런스와 유연한 샤프트로 손목 부담을 최소화한 수비형 라켓이다. 빠른 네트 플레이와 수비 위주 플레이에 적합하며, 체력이나 근력이 부족한 입문자와 여성 플레이어에게 특히 잘 맞는 모델이다.',
 false, false),

('mizuno-fortius-20',
 '미즈노 포르티우스 20(MIZUNO FORTIUS 20) 라켓',
 'MIZUNO', '10~15만원', '5U', 'head-heavy', 'stiff',
 ARRAY['초심자','D조'], ARRAY['공격형'],
 72, 58, 80, 75, 70, 78,
 '경량 5U 설계에 헤드헤비 밸런스를 결합해 빠르고 강한 스매시를 동시에 구현한 라켓이다. BEYOND FORCE SYSTEM 탑재로 스윙 속도와 타구력이 향상되며, 동호회 입문~D조 플레이어의 공격적 플레이에 잘 맞는다.',
 true, true),

('mizuno-fortius-50-spirit',
 '미즈노 포르티우스 50 스피릿(MIZUNO FORTIUS 50 SPIRIT) 라켓',
 'MIZUNO', '10~15만원', '4U', 'head-heavy', 'flexible',
 ARRAY['초심자','D조'], ARRAY['공격형'],
 70, 60, 68, 72, 68, 65,
 '일본산 HMG T46 소재와 유연한 샤프트로 강한 타구감과 부드러운 조작감을 함께 갖춘 라켓이다. 헤드헤비 밸런스로 스매시 파워를 높이면서도 Flexible 샤프트가 초심자의 팔꿈치 부담을 줄여준다.',
 false, false),

('mizuno-fortius-50-swift',
 '미즈노 포르티우스 50 스위프트(MIZUNO FORTIUS 50 SWIFT) 라켓',
 'MIZUNO', '10~15만원', '5U', 'head-heavy', 'stiff',
 ARRAY['D조'], ARRAY['공격형'],
 75, 55, 85, 75, 72, 80,
 '5U 초경량 바디에 Stiff 샤프트를 결합해 빠른 스윙과 강한 스매시를 극대화한 공격형 라켓이다. Rapid Response System이 반발력을 높여 상대 코트를 강하게 찌르는 플레이를 선호하는 D조에게 어울린다.',
 false, false),

('mizuno-fortius-11-power',
 '미즈노 포르티우스 11 파워(MIZUNO FORTIUS 11 POWER) 라켓',
 'MIZUNO', '10~15만원', '4U', 'head-heavy', 'stiff',
 ARRAY['D조','C조'], ARRAY['공격형'],
 85, 55, 72, 78, 80, 62,
 'TRANS FORCE FRAME과 롱샤프트 구조로 무게감 있는 강력한 스매시를 구현하는 공격형 라켓이다. 높은 관성 모멘트를 낮춰 스윙 회전 속도를 높인 설계로, 파워 스매시를 원하는 D조~C조 동호인에게 적합하다.',
 false, false),

('mizuno-altius-01-speed',
 '미즈노 알티우스 01 스피드(MIZUNO ALTIUS 01 SPEED) 라켓',
 'MIZUNO', '15만원+', '4U', 'even', 'medium',
 ARRAY['D조','C조'], ARRAY['올라운드'],
 72, 75, 82, 80, 75, 80,
 '이븐 밸런스와 미디엄 강성으로 빠른 스윙 속도와 정교한 컨트롤을 균형 있게 갖춘 미즈노 플래그십 라켓이다. M FUSION CARBON과 Aero Groove 기술로 공기 저항을 줄여 스피드 위주 올라운드 플레이에 최적화되어 있다.',
 true, true),

('mizuno-altius-03-control',
 '미즈노 알티우스 03 컨트롤(MIZUNO ALTIUS 03 CONTROL) 라켓',
 'MIZUNO', '15만원+', '4U', 'head-heavy', 'stiff',
 ARRAY['D조','C조'], ARRAY['올라운드'],
 78, 82, 68, 80, 75, 68,
 'Box Frame과 Xtra Slim Shaft의 조합으로 강한 스매시와 정밀한 컨트롤을 동시에 발휘하는 라켓이다. Stiff 샤프트가 스윙 에너지를 셔틀콕에 효율적으로 전달하여 D조~C조의 공수 겸비 플레이에 잘 맞는다.',
 true, false);
